- name: Set users, copy keys, and install fun software
  hosts: planetexpress
  connection: ssh
  gather_facts: yes  # Needed for apt module to work properly

  tasks:
  - name: bootstrapping
    become_method: su
    become: yes
    become_user: root

    block:
    # create new user on target system
    - name: Add user
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/bash
        system: no
        createhome: yes

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


- name: Install fun packages using shell
  hosts: planetexpress
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache
      shell: apt-get update

    - name: Install moon-buggy
      shell: apt-get install -y moon-buggy

    - name: Install cmatrix
      shell: apt-get install -y cmatrix

